### ISSUE TITLE
Export EPG to XMLTV for use with PLEX's Manual XMLTV Support

### ISSUE THREAD

**Issue by NightHammer1000** [OpenViX/HRTunerProxy#15]
Would it be Possible to create and serve a link to a XMLTV File to use with PLEX`s Manual XMLTV Support? 
It is a real pain in the ass to find a suiting Provider for SAT Channels and creating a file myself with Webgrab+ takes way to long. And why recreate the EPG with WebGrab+ if I already have it on the Box itself?

**Comment by andyblac** [comment]
no, as e2 does not have all the required info that plex needs.

**Comment by NightHammer1000** [comment]
Well. Than this is pretty much useless for SAT users until PLEX add real SAT EPG support. Thanks anyway.

**Comment by andyblac** [comment]
what is your provider ?, have you asked plex to add epg here https://forums.plex.tv/discussion/288325/no-plex-dvr-in-your-country-request-epg-data-for-your-country-here#latest

**Comment by NightHammer1000** [comment]
They dont Support DVB-S officially. And I dont have a Provider. I only use the free Channels. This Thread is only for Cable Providers.

**Comment by andyblac** [comment]
no, I use for FreeSat in UK with no issues. what is your epg your looking for ?, I'll have a word with plex.

**Comment by NightHammer1000** [comment]
Well we here use Astra 19,2E. If everything works out I plan to use ORF, HD+ and Sky. Everything I watch right now are Channels I can recive without a Provider. The Free German Channels.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Would be really cool ...

You can use these API Call on a Dreambox for getting EPG for a Service Reference : 

http://192.168.10.40/web/epgservice?sRef=1:0:19:283D:3FB:1:C00000:0:0:0:

(This is for Das Erste HD on Astra 19.2E)

Generating a XMLTV Url from selected Bouquet would be great!

**Comment by drdebian** [comment]
Indeed, it seems there isn't much missing from getting the TV guide info directly from the STB. Some folks already made attempts in solving this using an external Python script (i. e. http://forum.tv-mosaic.com/viewtopic.php?t=318#p1525 ), but getting the needed information straight out of HRTunerProxy running on the same STB anyway appears to be a much smoother approach.

**Comment by cvarelaruiz** [comment]
I've developed something around those lines (using the OpenWebif API to generate the XMLTV that you can pass to Plex instead of using the Gracenote's one which misses a bunch of my channels):

https://github.com/cvarelaruiz/owi2plex

**Comment by drdebian** [comment]
> I've developed something around those lines (using the OpenWebif API to generate the XMLTV that you can pass to Plex instead of using the Gracenote's one which misses a bunch of my channels):
> 
> https://github.com/cvarelaruiz/owi2plex

Very interesting, thanks for this!

**Comment by mensa84** [comment]
@NightHammer1000 Have you ever found a solution for that?

I also use Astra 19,2E satellite and don't need to have a "provider" for that.
Is there any plugin for Enigma2 or any other solution to get the EPG of the Box into XMLTV format?

**Comment by NightHammer1000** [comment]
> @NightHammer1000 Have you ever found a solution for that?
> 
> I also use Astra 19,2E satellite and don't need to have a "provider" for that. Is there any plugin for Enigma2 or any other solution to get the EPG of the Box into XMLTV format?

Nope. Never. Gave up on it and Plex all together and now use Jellyfin. Jellyfin has a native Enigma2 Plugin.

**Comment by mensa84** [comment]
Thanks. But Jellyfin doesn't have an Apple TV app, right?

**Comment by NightHammer1000** [comment]
> Thanks. But Jellyfin doesn't have an Apple TV app, right?

Dont know. Dont use Apple Devices because of how restrictive they are. Given that, no. Most likely not.

**Comment by mensa84** [comment]
> Jellyfin has a native Enigma2 Plugin.

Do you have a link for that native E2 plugin please?

**Comment by NightHammer1000** [comment]
> > Jellyfin has a native Enigma2 Plugin.
> 
> Do you have a link for that native E2 plugin please?

Add this repo
https://raw.githubusercontent.com/knackebrot/jellyfin-repo/master/manifest.json
