### ISSUE TITLE
VU+ Ultimo4K do not see DVB-S

### ISSUE THREAD

**Issue by Bl00d-B0b** [OpenViX/HRTunerProxy#16]
Hello,

I install HRTunerProxy on my Vu+ Ultimo4K. Hele is the list of my tuners:

Tuner A	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): 36.0° E
Tuner B	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): loopback to A
Tuner C	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): inactive
Tuner D	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): inactive
Tuner E	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): inactive
Tuner F	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): inactive
Tuner G	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): inactive
Tuner H	Vuplus DVB-S NIM(45208 FBC) (DVB-S2): inactive
Tuner I	Vuplus DVB-T NIM(SSH108) (DVB-T2)

But when I want to configure source I can choose only Antenna or Multi... So I Do not see any DVB-S channels

If I Choose antenna, then I see 1 Tuner 37 channels, 
If I choose multi, then I see 9 tuners but steel same 37 channels.

I try to use v3.2 and now install 3.3 same results :( 

Maybe you can help?

**Comment by andyblac** [comment]
post a screen shot of your config. I use a ultimo4k with 2 FBC tuners HRTunerProxy see all 16 tuners.

**Comment by Bl00d-B0b** [comment]
The channels are scanned. total I have more than 350 channels. But channels not in English language. where e2 log is located? attached some configs from my box. Also I use custom satellite.xml file for fast scanning. I attach a lot of files. but because I have both DVB-S + DVB-T my lastscanned file have only channels from DVB-T
[New folder.zip](https://github.com/OpenViX/HRTunerProxy/files/1481714/New.folder.zip)

**Comment by andyblac** [comment]
what image are you using ?

**Comment by Bl00d-B0b** [comment]
System OE: OE-Alliance 4.0 
Firmware version: OpenViX 5.0.032 (2017-10-25) 
Kernel / Drivers: 3.14.28 / 20170831

**Comment by Bl00d-B0b** [comment]
Hello.

I do not have any bouquets. only file I have is lastscanned bouquets, which is done automaticly. let me add some channels to bouquets and test.

**Comment by Bl00d-B0b** [comment]
Solved. Reason was simple. I do not have any bouquets. only default was created: lastscanned. and because I scan DVB-S and then DVB-T my lastscanned bouquet include only DVB-T channels. now I create custom, and it's works as expected. thanks for help

**Comment by Huevos** [comment]
On 36.0E is it a proper provider that supplies these channels (with a dedicated set top box), or is it just a random group of channels from different providers? If it is a proper provider we may be able to create a bouquet with AutoBouquetsMaker.

**Comment by Bl00d-B0b** [comment]
https://www.lyngsat.com/Eutelsat-36B-and-Express-AMU1.html there are two major providers: Tricolor & NTV. and AutoBouquetMaker does not help. but I can create myself, no problem
