### ISSUE TITLE
Teletext showing when viewing/recording same channels

### ISSUE THREAD

**Issue by chiefjoejj** [OpenViX/HRTunerProxy#19]
Hi guys,
while live viewing or recording some channels (like "Pro7 HD") the Plex Player does not show the acutal program but the teletext of that channel, which shows different teletext pages (changing like every second or so). Audio is working fine at the same time. Other channels like "Das Erste HD" are working without any issues. Did somebody have the same problem and/or any idea what is going wrong here?

Greetz
Jay

**Comment by rickardrockard** [comment]
I had the same problem, and it's a Plex issue not related to the plugin. Try, using the web ui, going to Settings -> Server -> Languages and deselect "Automatically select audio and subtitle tracks". I also set "Subtitle mode" to "Manually selected".

**Comment by chiefjoejj** [comment]
Hi rickardrockard,
thanks a lot for your advice. That did the trick! When disabling the auto subtitle functions it now works as expected, even when I set the language to German. Unfortunately that is still just a workaround because I normally want to watch movies and series (apart from the AVR function) in English with matching forced subtitles - and this was my default setting since ever. Let's see if this problem is being addressed sometime. I really would appreciate it since teletext is totally unnecessary.
