### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by RobvanderDoes** [OpenViX/HRTunerProxy#22]
Translations do not work. I added the Dutch translation the same way as I do for other ViX-repos, but no Dutch translation shows.

**Comment by andyblac** [comment]
have you placed the file in the correct location ? need to as follows

`/usr/lib/enigma2/python/Plugins/SystemPlugins/HRTunerProxy/locale/nl/LC_MESSAGES/HRTunerProxy.mo`

**Comment by RobvanderDoes** [comment]
Yep, and that works, but that wasn't my issue.
Seeing https://github.com/OpenViX/HRTunerProxy/commit/a26e2e96e0ce2f4fbfa9dce6d8489b0a0f52b658 I understand that po's here work quite different from other plugins & ViX.
OK, fine, I'll close the issue.
