### ISSUE TITLE
DM920 - Device not found Ensure your device is powered on and connected to your network. Issue in plex

### ISSUE THREAD

**Issue by gelsas** [OpenViX/HRTunerProxy#32]
Hello,

i am running the latest version of the plugin on my dm920 with latest newnigma image. 

I configured everything via the plugin, but the dvr only shows up very short and then disappears again.

"Device not found Ensure your device is powered on and connected to your network."
what can i do?

**Comment by Man-in-Black** [comment]
I got the same problem.
Problem of HRTunerProxy or Plex itself?
