### ISSUE TITLE
second server serves blank XML

### ISSUE THREAD

**Issue by chenks** [OpenViX/HRTunerProxy#41]
when i set up hrtunerproxy on my enigma2 box, i have 1 for cable and 1 for IPTV. it seems to create the second server and provides the IP and port number for both servers, prompts to reboot.

after reboot the cable server provides a valid XML file on 192.168.1.3:6081, but the IPTV server on 192.168.1.3:6085 does provide a blank XML which means it serves nothing.

am i missing something here or is this a bug?

**Comment by fridayshoes** [comment]
I don’t think hrtunerproxy supports serving iptv sources

**Comment by chenks** [comment]
It gives you the option to serve IPTV, it's there is in the list of options.

Also my IPTV source is integrated into bouquets on the enigma2 box
