### ISSUE TITLE
SystemPlugins/HRTunerProxy (invalid literal for int () with base 10:")

### ISSUE THREAD

**Issue by Tuppe28** [OpenViX/HRTunerProxy#45]
Hi,

Been using the plugin for a while with no issues, thanks.

However am now getting error below.  Have tried update, rollback, uninstall and re-install plugin and error persists.

Some plugins are not available
SystemPlugins/HRTunerProxy (invalid literal for int () with base 10:")

Box info

System OE: | OE-Alliance 4.4
Firmware version: | OpenViX 5.4.006 (2021-02-08)
Kernel / Drivers: | 4.11.0 / 20171106

Any help or guidance on what I can try would be much appreciated.

Thanks

**Comment by AbuBaniaz** [comment]
Suggested fix uploaded to your thread on forum

**Comment by Tuppe28** [comment]
> Suggested fix uploaded to your thread on forum

Thanks very much.

**Comment by AbuBaniaz** [comment]
A slightly different fix has been committed. https://github.com/OpenViX/HRTunerProxy/commit/9659b0ee52e9b10eedf462d1d54d68eb84274848

Please re-open issue if problem persists
