### ISSUE TITLE
Cant install/load plugin on Vu+ Zero4K (No module named six)

### ISSUE THREAD

**Issue by mStirner** [OpenViX/HRTunerProxy#55]
I downloaded the repo, renamed the plugin folder to "HRTunerProxy" and copied it via `scp` to `/usr/lib/enigma2/python/Plugins/SystemPlugins`.

After rebooting, i wanted to start the plugin and got the following error message:

![grafik](https://github.com/OpenViX/HRTunerProxy/assets/5003424/b7f32fad-5e79-44c6-8c14-1251c55d375c)

How can i install the six module and other dependencies?
The receiver i use is a [Vu+ Zero4K](https://www.vuplus.de/zero-4k)

Python version is `2.7.9`

```
root@vuzero4k:~# cat /etc/os-release 
ID=vuplus
NAME=vuplus
VERSION=3.0.0
VERSION_ID=3.0.0
PRETTY_NAME=vuplus 3.0.0

**Comment by TwolDE2** [comment]
Update the vix image …. We use python 3

**Comment by Huevos** [comment]
Where did yo get that image from? What image/distro is it?

**Comment by TwolDE2** [comment]
Our image link for your box is here…..
https://www.openvix.co.uk/index.php/downloads/vu-plus-images/vu-zero-4k/
But better to post new thread here, so we can help…..
https://www.world-of-satellite.com/search.php?do=getnew&contenttype=vBForum_Post

**Comment by mStirner** [comment]
> Where did yo get that image from? What image/distro is it?
Is the stock one.

> Our image link for your box is here….. https://www.openvix.co.uk/index.php/downloads/vu-plus-images/vu-zero-4k/ 
Flashed it and the plugin works after a bit of work in plex.
Now i have to deal with plex and the EPGXML crap :roll_eyes: 
But this is not a issue of this plugin.

Thaks for the great work and help.
Have all a nice Sunday!
